sudo: required
dist: trusty
language: generic
services:
  - docker
script:
  - make docker-test
cache:
  directories:
    - /var/lib/docker
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    on_pull_requests: false
    secure: mGqCgRCFMB89AKsYVOZI79sifCFOLaQkuY3rvFKMitpD1GYQQpkBbZ9Z1SWi0VQV63oOKTQBrPCeDSwhZMaJA/dCZZIuz6e9nkVyJJUIrqAuH9PjgQr6FM4FkKzVLpHdPnXIikAvUAKiPRzzj8z4KO1EohBRR/xb2/4TpoWrkSA=
